### ISSUE TITLE
demo download

### ISSUE THREAD

**Issue by JDeuce** [joshuaferrara/node-csgo#1]
Hey man this looks like a sweet project. I really want some api that will let me automatically download my recent demos from matchmaking. Have you thought about adding the demo list to this?

**Comment by joshuaferrara** [comment]
I've not thought of adding that in yet. As of writing this comment I'm not even sure if it's possible but ill take a look in a few hours.

**Comment by JDeuce** [comment]
Alright,the only thing I know for sure is once you select a demo for download, the client goes out over regular http to a URL like http://replay114.valve.net/730/003049563753109520390_1479899742.dem.bz2.  

My guess is that it uses some request like the ones you've been tapping into to get some list of matches, and somehow piece together the URLs... but I haven't dug into it yet.

**Comment by joshuaferrara** [comment]
Added in commit a526b020bc3370e6d6dd87a9475a2bf24bb72f27

By using requestRecentGames, you will be able to get a list of recent matches given an accountId. Each match returned has a URL to the dem.bz2 file that you can download.

The readme has a lot more info on what is returned.
