### ISSUE TITLE
Request game info

### ISSUE THREAD

**Issue by TrueCarry** [joshuaferrara/node-csgo#12]
Do you think there's a way when we can use

``` javascript
message CMsgGCCStrike15_v2_MatchListRequestFullGameInfo {
    optional uint64 matchid = 1;
    optional uint64 outcomeid = 2;
    optional uint32 token = 3;
}
```

?  
I'm trying to make it work, but I have no matches in reponse. I think outcomeid is id of last round, but I have no clue what token value should be.

**Comment by joshuaferrara** [comment]
Interesting. I'll look into this later tonight as well as the pull request - which is honestly amazing and saves me a lot of work and I'm super thankful. 

I'll do some digging on what the message is used for and get some more info on it.

**Comment by joshuaferrara** [comment]
Interesting. I'll look into this later tonight as well as the pull request - which is honestly amazing and saves me a lot of work and I'm super thankful. 

I'll do some digging on what the message is used for and get some more info on it.

**Comment by joshuaferrara** [comment]
Yeah, no clue what it's used for. The GC is responding "0" for match_id's and I haven't seen the message used at all.

**Comment by joshuaferrara** [comment]
I'm gonna close this as we've conversed more about it in the Gitter room.
