### ISSUE TITLE
Text values returning null?

### ISSUE THREAD

**Issue by manmohanjit** [joshuaferrara/node-csgo#16]
Hey guys, I'm pretty newbie to node but I'm having this problem... where text fields are just showing null.

https://gist.github.com/riser-/96c161d2bfff1d011eeb

Code and response, any idea why?

Thanks!

**Comment by TrueCarry** [comment]
Text fields not showing null(check for map, it's displayed).

**Comment by manmohanjit** [comment]
Hmm.. I tried it using two accounts but from the output I posted I don't see any map names, am I doing something wrong?

**Comment by TrueCarry** [comment]
Open https://gist.githubusercontent.com/riser-/96c161d2bfff1d011eeb/raw/4ee95098421a026004321d2b2e4413a5668a1346/gistfile2.txt
and search for "map":"http://replay153.valve.net/730/003075844273594171555_0542920635.dem.bz2"

**Comment by manmohanjit** [comment]
Oh. yeah I found that, I just thought that Valve also included map name and stuff.. guess I was wrong.

Thanks!
