### ISSUE TITLE
About the number on richPresenceUpload

### ISSUE THREAD

**Issue by rodjun** [joshuaferrara/node-csgo#19]
According to the console command "version", that value is the Protocol version, which (at least at the current update) is the same as the EXE version but without points.

So maybe it's required to make sure that the client is on the latest version? 

Here's what the current "version" looks like:

Protocol version 13504
Exe version 1.35.0.4 (csgo)
Exe build: 17:12:46 Sep 30 2015 (6171) (730)

This is not really an issue (apart from the fact that the example is now outdated (13503 instead of 13504), just some info on the number.

**Comment by joshuaferrara** [comment]
Thanks, just shared this on the [node-csgo Gitter](https://gitter.im/joshuaferrara/node-csgo).
