### ISSUE TITLE
Event playerProfile problem

### ISSUE THREAD

**Issue by prugala** [joshuaferrara/node-csgo#23]
Hello

Im on event "friend" from node-steam call:
CSGO.playerProfileRequest(CSGO.ToAccountID(sid));
        CSGO.on("playerProfile", function(profile) {
             //get player profil info
}

I have a problem when check first friend is ok, but when I add second friend "playerProfile" is calling two times for first and second friend.

How can I fix it?

**Comment by TrueCarry** [comment]
I guess you are misunderstanding "friend" event.

**Comment by prugala** [comment]
My friend event is with if for new friend requests only:

steamFriends.on('friend', function(userId, relationship) { 
    if (relationship == steam.EFriendRelationship.RequestRecipient) {
        steamFriends.addFriend(userId);

```
    setTimeout(function() {
        steamFriends.sendMessage(userId, welcomeMessage);

        setTimeout(function() {
            getPlayerRank(userId); //in this method I have csgo events from first post.
        }, 2000);
    }, 3000);
}
```

});
