### ISSUE TITLE
Getting empty account_profiles with playerProfileRequest()

### ISSUE THREAD

**Issue by ghost** [joshuaferrara/node-csgo#31]
Hi, first off, full code:
http://pastebin.com/Jn1xuJuQ

So I wait for any friend to start CS:GO. If it happened, I try to request profile. This is the result: https://gyazo.com/026fe3ca605964d1cb93c753ea49a06a

So it fails with friendObj.friendid

But the stupid thing is... with steamClient.steamID it works.

I already discussed this with a guy in gitter but he couldnt help me :/ We tried much...

**Comment by ghost** [comment]
I just checked a little more and I did the following:

`steamCSGO.playerProfileRequest(steamCSGO.ToAccountID("76561197961181950"));
                steamCSGO.playerProfileRequest(steamCSGO.ToAccountID("76561198047656273"));
                steamCSGO.playerProfileRequest(steamCSGO.ToAccountID("76561198274952423"));
                steamCSGO.playerProfileRequest(steamCSGO.ToAccountID("76561198036811229"));`

ALL of them are accounts ON my friend list and they ALL ran CS:GO when I tested it. But only number 1 and 3 were getting normal results. The other two were empty again....

**Comment by joshuaferrara** [comment]
Have you checked to see if ToAccountID is returning correct account IDs?
Could be some edge cases with conversion we are unaware of.

**Comment by ghost** [comment]
Yes I checked that. Seems fine:
https://gyazo.com/373dc059e90840defa4d903f1804027f

friendObj.friendid not working
steamClient.steamID working

**Comment by joshuaferrara** [comment]
Did you pause for a couple of seconds in between requests?

**Comment by ghost** [comment]
Tried that too already. No success.

It really seems that for some steamIDs it works and for some it doesnt. I picked two steam IDs from friends that were online and ingame and called playerProfileRequest on both and the one always worked and the other one always failed.

So I continued and took random other steam ids from friends that were online and ingame and I couldnt find a pattern or something. Some work, some dont.

**Comment by ghost** [comment]
Okay, I no longer think this has to do with node-csgo.

I found out: It DOESNT work with steam-accounts that have CS:GO started by using a node-js idle bot. I checked it by going ingame myself and click the "show CSGO profile" on my friends. There was NO data. The only guys that was really online and ingame I got the correct result from...

But is that plausible? Shouldnt it work either way?

**Comment by TrueCarry** [comment]
No, since bots not completely emulating game client.

**Comment by ghost** [comment]
Alright so this can be closed i guess... One last question: Why does playerProfileRequest return "account_profiles"? Can a single steam account have multiple cs:go profiles?

**Comment by TrueCarry** [comment]
Because you can recieve packet with account profiles from many requests, not only playerProfileRequest, and some of them can request multiple accounts, I guess. Or you would be able in the future.

**Comment by joshuaferrara** [comment]
> I found out: It DOESNT work with steam-accounts that have CS:GO started by using a node-js idle bot. I checked it by going ingame myself and click the "show CSGO profile" on my friends. There was NO data. The only guys that was really online and ingame I got the correct result from...

Nice find. Might need to document this somewhere in the future.
