### ISSUE TITLE
How can I get infos from matches?

### ISSUE THREAD

**Issue by Raphash0w** [joshuaferrara/node-csgo#36]
Hey guys, 
Basicaly I want to get infos from the matches that my own cs:go servers will do... Infos like: kills, deaths, assists, etc...

I heard about that Valve let we do a request each 60 seconds to pull those infos to my website?

Thank soo much guys!

**Comment by joshuaferrara** [comment]
Please ask your question in the [node-csgo Gitter](https://gitter.im/joshuaferrara/node-csgo). There's a lot more people who watch it and we like to reserve issues for bugs within node-csgo.
