### ISSUE TITLE
requestGame() returns null

### ISSUE THREAD

**Issue by Viiprogrammer** [joshuaferrara/node-csgo#38]
```
var Steam = require('steam'),
    steamClient = new Steam.SteamClient(),
    steamUser = new Steam.SteamUser(steamClient),
    steamGC = new Steam.SteamGameCoordinator(steamClient, 730),
    csgo = require('csgo'),
    CSGO = new csgo.CSGOClient(steamUser, steamGC, false);

var decoded = new csgo.SharecodeDecoder("CSGO-7UvAK-FD3Ac-8DeTA-74ZUK-9Sm6J").decode();
console.log(decoded);
var requestinfo = CSGO.requestGame(decoded.matchId, decoded.outcomeId, decoded.tokenId);
console.log(requestinfo);
```

requestGame() returns null :(
![screenshot_3](https://cloud.githubusercontent.com/assets/17622604/16115556/6cb36d18-33d0-11e6-9e2d-5826161ad03c.png)

**Comment by TrueCarry** [comment]
Because this function uses callback. GitHub issues is for issues, if you have problems with coding, you should use gitter.

**Comment by joshuaferrara** [comment]
Like @TrueCarry said, please use [our gitter room](https://gitter.im/joshuaferrara/node-csgo) in the future for technical questions.

In regards to your issue, [you need to be listening for the `matchList` event when you use `requestGame`.](https://github.com/joshuaferrara/node-csgo#requestgamestring-matchid-string-outcomeid-int-token)
