### ISSUE TITLE
node-steam connect socket timeout

### ISSUE THREAD

**Issue by wa1one** [joshuaferrara/node-csgo#56]
Unable to connect SteamClient to steam servers

Debug: 
connecting to 162.254.196.41:27017
socket timed out
socket closed
connecting to 162.254.196.40:27020
socket timed out
socket closed

**Comment by joshuaferrara** [comment]
Can’t do any further research today, but this is likely https://github.com/seishun/node-steam/issues/434

**Comment by wa1one** [comment]
Yeah, thank you, resolved!
