### ISSUE TITLE
GC Connection went missing, exiting

### ISSUE THREAD

**Issue by sebastiandev19** [joshuaferrara/node-csgo#57]
22 Feb 17:05:52 - GC Connection went missing, exiting
After Loggued i get this error.

**Comment by joshuaferrara** [comment]
[No issues on my end](https://travis-ci.org/joshuaferrara/node-csgo/builds/494692398). I've added a `servers.json` file for the example directory which might be a part of the issue you're running into.

If you continue to have issues, feel free to post your code and output and I'll try and take a look.
