### ISSUE TITLE
How to get sharecode for a given match?

### ISSUE THREAD

**Issue by haihala** [joshuaferrara/node-csgo#59]
I think I've figured out how to extract the matchId and the reservationId of the last round which I assume to be the outcomeId, but I have no clue how to get the token. I dumped the entire match into a file and tried to search for token or even the token I manually extracted from one sharecode but neither found anything.

I also failed to find the sharecode encoder if such a thing exists.

**Comment by joshuaferrara** [comment]
Unfortunately node-csgo does not have any sharecode encoding functionality. I did a quick search and found [csgo-sharecode](https://www.npmjs.com/package/csgo-sharecode) which seems like it would work for your use case. Ideally, it would be great to have node-csgo use this library for our sharecode encoding/decoding at some point in the future.
