### ISSUE TITLE
Prime status?

### ISSUE THREAD

**Issue by futdev** [joshuaferrara/node-csgo#62]
Hi, would it be possible to find the prime status of a given user?

**Comment by joshuaferrara** [comment]
node-csgo currently doesn't support this.

I briefly looked into the [protobuf definitions](https://github.com/SteamDatabase/Protobufs/tree/master/csgo) to see if this could become a feature and I don't believe it's possible. I've linked the files above; if you happen to find anything that seems to indicate a users prime status let me know and it can be added.

**Comment by jslno** [comment]
You could make a prime only server and verify the status.
