### ISSUE TITLE
Get match details from requestCurrentLiveGames

### ISSUE THREAD

**Issue by Henroks** [joshuaferrara/node-csgo#64]
Through _requestCurrentLiveGames_ I only can gather match_id, I would like to wait for them to wait and download its replay. Is there a way to get outcomeId and tokenId from those matches? Its easy to wait for them to end, but I don't know how to get the token or the outcome

**Comment by joshuaferrara** [comment]
Q&A should be handled in the Gitter chat room: https://gitter.im/joshuaferrara/node-csgo
