### ISSUE TITLE
Version 1.5.13 is broken because of steam-resources

### ISSUE THREAD

**Issue by EloB** [joshuaferrara/node-csgo#68]
`steam-resources` has a `prepare` script in their `package.json` that uses `svn` to clone stuff on installation.

When I try to do a fresh installation without `node_modules` it fails to install. Not every server has `svn` installed on their machines...

**Comment by EloB** [comment]
Version (1.5.13) should be a major version because of the `steam-resources` or you have to add back the `node_modules` folder again.

**Comment by EloB** [comment]
See old version
https://unpkg.com/browse/csgo@1.5.12/

See new version (without `node_modules`)
https://unpkg.com/browse/csgo@1.5.13/

**Comment by joshuaferrara** [comment]
Yeah, this should be handled by `steam-resources` being a bundled dependency, but seems like it got caught up somehow...

Will have to do a bit more research into this when time allows.

**Comment by joshuaferrara** [comment]
You’re doing the fresh installation with `npm` as opposed to cloning the repo, correct?

**Comment by EloB** [comment]
I've tried both `yarn` and `npm` both failed.

**Comment by EloB** [comment]
A workaround at the moment is to install `svn` locally but I think there should be a better solution.

You can manually goto the folder and run `yarn prepare` or `npm run prepare`. If you have problems with the package.

**Comment by EloB** [comment]
When using version `1.21.1` of `yarn` it never runs the `prepare` script. That fails everything. The files are missing and the package is broken.

When using version `6.13.4` of `npm` it will run the `prepare` script and then fails if `svn` doesn't exist.

Both ways it's pretty broken I would say.

**Comment by EloB** [comment]
Even when I ran that `svn` command locally it doesn't work. My site is totally broken because if this. `requestLiveGameForUser` doesn't work be for with this thing. I'm on a Windows machine I don't know if it's related or not.

**Comment by EloB** [comment]
I don't know how we can fix this because the owner of the library doesn't want to fix this.

https://github.com/seishun/node-steam-resources/issues/9

I managed to install on my production server at the moment but I need `svn` on that server too. Even if this is a dependency of a dependency. His `prepare` script always run no matter what. He marked my ticket as spam. So I don't think he will update it.

You have to write to the guy or add to the `README` that you need to have `svn` always installed on every device.

**Comment by EloB** [comment]
When do you have time to fix this? The owner of `node-steam-resources` claims that it will solve if the `node_modules` exist. This is a blocker at the moment.

**Comment by joshuaferrara** [comment]
No ETA. Revert to 1.5.12 if it’s causing an issue for now.

**Comment by joshuaferrara** [comment]
Fixed in 06ef650.
I'm unsure of the circumstances, but your tone came off as quite pushy. Please try and be a bit more respectful next time. I'm sure you're aware that open source projects are typically contributed to in ones free-time, so please don't expect any type of SLA from me or others.
