### ISSUE TITLE
SharecodeDecoder not working

### ISSUE THREAD

**Issue by peterfranzo** [joshuaferrara/node-csgo#73]
The sharecode decover is not working for me:

`

> var Steam = require('steam');
> var csgo = require('csgo')
> 
> var steamClient = new Steam.SteamClient();
> var steamUser = new Steam.SteamUser(steamClient);
> steamClient.connect();
> steamClient.on('connected', function() {
>   steamUser.logOn({
>     account_name: 'redacted',
>     password: 'redacted'
>   });
> });
> 
> 
> steamClient.on('logOnResponse', function() {
> 	steamGC = new Steam.SteamGameCoordinator(steamClient, 730);
> 	CSGO = new csgo.CSGOClient(steamUser, steamGC, false);
> 	
> 	console.log(CSGO.SharecodeDecoder("CSGO-U6MWi-hYFWJ-opPwD-JciHm-qOijD").decode());
> });

`

this results in 
![image](https://user-images.githubusercontent.com/64496311/92587097-75e2c200-f297-11ea-80b0-9c4cebe2996b.png)

**Comment by joshuaferrara** [comment]
You should be making a new instance of the `SharecodeDecoder` from the `csgo` import (not your `CSGO` instance). 

You're also missing a `new` before `csgo.SharecodeDecoder`; from the example.js file:
```
/* Decoding Share Codes */
var scDecoder = new csgo.SharecodeDecoder("CSGO-U6MWi-hYFWJ-opPwD-JciHm-qOijD");
console.log("Sharecode CSGO-U6MWi-hYFWJ-opPwD-JciHm-qOijD decodes into: ");
console.log(scDecoder.decode());
```
