### ISSUE TITLE
Cannot find file: Resource errors

### ISSUE THREAD

**Issue by alandsilva26** [joshuaferrara/node-csgo#74]
![image](https://user-images.githubusercontent.com/47769063/94612482-ca8ac300-02c0-11eb-8e13-10456ececacf.png)

**Comment by joshuaferrara** [comment]
are you trying to run node-csgo in the browser? if so, that's not supported. you'll need to have some backend server running node-csgo and a communication channel in between your front and backend to make that work. feel free to re-open if that's not the case.
