### ISSUE TITLE
steamGameCoordinator never accept ClientHello

### ISSUE THREAD

**Issue by samyycX** [joshuaferrara/node-csgo#80]
i enable the debug mode, and it always return Sending ClientHello, the ready event never trigger.

i have connected to the steamClient and logon a steamuser.

**Comment by joshuaferrara** [comment]
just ran the example on my end and I'm not seeing the same issue. if you continue to run into this issue, re-open this and include the code that's causing you trouble along with the output.

**Comment by funmaker** [comment]
@joshuaferrara I'm having the same issue.

My code: https://pastebin.com/H9fCSubE
It's more or less just the example script.

Output:
```
Username: ******************
Password: ********************
31 Jan 23:59:37 - Logged in!
31 Jan 23:59:37 - Logged on.
31 Jan 23:59:37 - Launching CS:GO
31 Jan 23:59:37 - Received servers.
31 Jan 23:59:40 - Sending ClientHello
31 Jan 23:59:42 - Sending ClientHello
31 Jan 23:59:45 - Sending ClientHello
31 Jan 23:59:47 - Sending ClientHello
31 Jan 23:59:50 - Sending ClientHello
31 Jan 23:59:52 - Sending ClientHello
31 Jan 23:59:55 - Sending ClientHello
31 Jan 23:59:57 - Sending ClientHello
1 Feb 00:00:00 - Sending ClientHello
1 Feb 00:00:02 - Sending ClientHello
1 Feb 00:00:05 - Sending ClientHello
1 Feb 00:00:07 - Sending ClientHello
```
And it goes on like that without ever firing `ready` event. node-dota2 works fine.
