### ISSUE TITLE
Stuck at Sending ClientHello

### ISSUE THREAD

**Issue by funmaker** [joshuaferrara/node-csgo#82]
I have basically same issue as discussed in recently closed #80 
When I try to launch node-csgo it gets stuck at Sending ClientHello, never firing `ready` event.

My code: https://pastebin.com/H9fCSubE
It's more or less just the example script.

Output:
```
Username: ******************
Password: ********************
31 Jan 23:59:37 - Logged in!
31 Jan 23:59:37 - Logged on.
31 Jan 23:59:37 - Launching CS:GO
31 Jan 23:59:37 - Received servers.
31 Jan 23:59:40 - Sending ClientHello
31 Jan 23:59:42 - Sending ClientHello
31 Jan 23:59:45 - Sending ClientHello
31 Jan 23:59:47 - Sending ClientHello
31 Jan 23:59:50 - Sending ClientHello
31 Jan 23:59:52 - Sending ClientHello
31 Jan 23:59:55 - Sending ClientHello
31 Jan 23:59:57 - Sending ClientHello
1 Feb 00:00:00 - Sending ClientHello
1 Feb 00:00:02 - Sending ClientHello
1 Feb 00:00:05 - Sending ClientHello
1 Feb 00:00:07 - Sending ClientHello
```

However node-dota2 works fine.

**Comment by PixLSteam** [comment]
I'm not using *this* module, but I'm having the same issue - I never get a client welcome from the GC. Did something change about this process recently? Edit: Apparently, the GC was having some trouble.

**Comment by funmaker** [comment]
Apparently you have to run the game at least once on that account to be able to use this library. This should be in the README

**Comment by joshuaferrara** [comment]
> Apparently you have to run the game at least once on that account to be able to use this library. This should be in the README

Feel free to make a PR 😄
